name: anamic
channels:
    - conda-forge

dependencies:
    - python>=3.6
    - numpy
    - scipy
    - matplotlib
    - pandas
    - pytables
    - jupyter
    - jupyterlab
    - notebook
    - ipywidgets
    - tifffile
    - nose
    - pyyaml
    - ipyvolume
    - tqdm
